spring:
  application:
    name: selfDevProject

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.45.110:3306/challengedb?characterEncoding=utf8
    username: challengeuser
    password: challenge

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:/mapper/*.xml

server:     # accesslog 확인 용도
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: common
      buffered: false